### ISSUE TITLE
geosteiner

### ISSUE THREAD

**Issue by edljk** [leethargo/PipeLayout.jl#14]
Is it already possible to call geosteiner with PipeLayout.jl
? If not, is it planed? Thanks.

**Comment by leethargo** [comment]
Yes, it's implemented, see the [corresponding test](https://github.com/leethargo/PipeLayout.jl/blob/master/test/topology/geosteiner.jl).

For that to work, GeoSteiner needs to be installed on your system.
This is tested by [has_geosteiner](https://github.com/leethargo/PipeLayout.jl/blob/master/src/topology/geosteiner.jl#L2).

**Comment by leethargo** [comment]
That makes sense, since it's an index into an array and that code was translated directly from a previous Python code. Still, I'm confused why the test case works then, since it also involves terminal nodes (case `T`). I would have to look again at the text output of GeoSteiner to be sure :fearful:.

Do you have a failing example?
